export const WARD_2026_CALENDAR: { date: string; activity: string; organisation: string; }[] = [
  { date: "2026-01-17", activity: "RELIEF SOCIETY KEEP FIT ACTIVITY", organisation: "RELIEF SOCIETY" },
  { date: "2026-01-24", activity: "PRIMARY SPORT ACTIVITY", organisation: "PRIMARY" },
  { date: "2026-01-25", activity: "SUNDAY SCHOOL TRAINING FOR TEACHERS", organisation: "SUNDAY SCHOOL" },
  { date: "2026-01-25", activity: "NEW AND RETURNING MEMBERS DEVOTIONAL/FIRESIDE", organisation: "WARD" },
  { date: "2026-01-31", activity: "YOUTH DEVOTIONAL", organisation: "YOUTH" },
  { date: "2026-02-01", activity: "SELF RELIANCE DEVOTIONAL", organisation: "WARD" },
  { date: "2026-02-07", activity: "YSA GOSPEL FIRESIDE ACTIVITY", organisation: "YSA" },
  { date: "2026-02-21", activity: "ELDERS QUORUM REACTIVATION EXERCISE", organisation: "ELDERS QUORUM" },
  { date: "2026-02-21", activity: "YOUNG MEN SKILL ACQUISITION (SHOE MAKING)", organisation: "YOUNG MEN" },
  { date: "2026-03-07", activity: "PRIMARY MUSIC ACTIVITY", organisation: "PRIMARY" },
  { date: "2026-03-07", activity: "YOUNG MEN SPORT", organisation: "YOUNG MEN" },
  { date: "2026-03-16", activity: "YSA PIZZA APPRAISAL NIGHT", organisation: "YSA" },
  { date: "2026-03-21", activity: "ELDERS QUORUM SPORTING ACTIVITY", organisation: "ELDERS QUORUM" },
  { date: "2026-03-21", activity: "RELIEF SOCIETY ANNIVERSARY", organisation: "RELIEF SOCIETY" },
  { date: "2026-03-26", activity: "WARD FAMILY HISTORY WORKSHOP", organisation: "WARD" },
  { date: "2026-03-28", activity: "WARD MISSIONARY FIRESIDE/REACTIVATION ACTIVITIES", organisation: "WARD" },
  { date: "2026-03-29", activity: "WARD TEMPLE AND FAMILY HISTORY DEVOTIONAL", organisation: "WARD" },
  { date: "2026-04-06", activity: "YSA EASTER PICNIC/ DEVOTIONAL", organisation: "YSA" },
  { date: "2026-04-06", activity: "YOUNG MEN EASTER PICNIC", organisation: "YOUNG MEN" },
  { date: "2026-04-12", activity: "WARD CONFERENCE", organisation: "WARD" },
  { date: "2026-04-25", activity: "YOUNG WOMEN TALENT AND CULTURAL DAY", organisation: "YOUNG WOMEN" },
  { date: "2026-04-26", activity: "NEW AND RETURNING MEMBERS DEVOTIONAL/FIRESIDE", organisation: "WARD" },
  { date: "2026-05-09", activity: "RELIEF SOCIETY KNOCK ON DOOR", organisation: "RELIEF SOCIETY" },
  { date: "2026-05-16", activity: "ELDERS QUORUM GET TOGETHER/ FINANCIAL MANAGEMENT SEMINAR", organisation: "ELDERS QUORUM" },
  { date: "2026-05-16", activity: "PRIMARY CRAFT ACTIVITY", organisation: "PRIMARY" },
  { date: "2026-05-27", activity: "YOUTH TEMPLE AND FAMILY HISTORY ACTIVITY", organisation: "YOUTH" },
  { date: "2026-06-07", activity: "ALL ENDOWED MEMBERS DEVOTIONAL", organisation: "WARD" },
  { date: "2026-06-13", activity: "YOUNG MEN MISSIONARY/REACTIVATION ACTIVITY", organisation: "YOUNG MEN" },
  { date: "2026-06-20", activity: "ELDERS QUORUM SERVICE PROJECT ACTIVITY", organisation: "ELDERS QUORUM" },
  { date: "2026-06-20", activity: "YSA SPORT ACTIVITY", organisation: "YSA" },
  { date: "2026-06-21", activity: "SUNDAY SCHOOL TEACHER TRAINING MEETING", organisation: "SUNDAY SCHOOL" },
  { date: "2026-06-25", activity: "WARD FAMILY HISTORY WORKSHOP", organisation: "WARD" },
  { date: "2026-06-27", activity: "RELIEF SOCIETY WARD SERVICE PROJECT", organisation: "RELIEF SOCIETY" },
  { date: "2026-06-28", activity: "WARD TEMPLE AND FAMILY HISTORY DEVOTIONAL", organisation: "WARD" },
  { date: "2026-07-04", activity: "PRIMARY CAREER DAY ACTIVITY", organisation: "PRIMARY" },
  { date: "2026-07-04", activity: "YSA WORKSHOP", organisation: "YSA" },
  { date: "2026-07-11", activity: "WARD MISSIONARY FIRESIDE/REACTIVATION ACTIVITIES", organisation: "WARD" },
  { date: "2026-07-18", activity: "RELIEF SOCIETY ENRICHMENT ACTIVITY", organisation: "RELIEF SOCIETY" },
  { date: "2026-07-18", activity: "YOUNG MEN HEALTH TALK", organisation: "YOUNG MEN" },
  { date: "2026-07-25", activity: "WARD HEALTH AND WELLNESS DAY", organisation: "WARD" },
  { date: "2026-07-26", activity: "NEW AND RETURNING MEMBERS DEVOTIONAL/FIRESIDE", organisation: "WARD" },
  { date: "2026-08-01", activity: "YOUNG WOMEN REACTIVATION", organisation: "YOUNG WOMEN" },
  { date: "2026-08-02", activity: "SELF RELIANCE DEVOTIONAL", organisation: "WARD" },
  { date: "2026-08-15", activity: "YOUNG MEN SKILL ACQUISITION (ICT)", organisation: "YOUNG MEN" },
  { date: "2026-08-22", activity: "ELDERS QUORUM IN THE KITCHEN", organisation: "ELDERS QUORUM" },
  { date: "2026-08-29", activity: "YOUTH SCRIPTURAL CHALLENGE", organisation: "YOUTH" },
  { date: "2026-09-05", activity: "YOUNG MEN SKILL ACQUISITION (BARBING)", organisation: "YOUNG MEN" },
  { date: "2026-09-05", activity: "PRIMARY MUSIC ACTIVITY", organisation: "PRIMARY" },
  { date: "2026-09-05", activity: "YSA DEVOTIONAL/ CLEANING PROJECT", organisation: "YSA" },
  { date: "2026-09-19", activity: "ELDERS QUORUM SKILL ACQUISITION", organisation: "ELDERS QUORUM" },
  { date: "2026-09-19", activity: "RELIEF SOCIETY MISSIONARY DEVOTIONAL", organisation: "RELIEF SOCIETY" },
  { date: "2026-09-20", activity: "TEACHER TRAINING MEETING", organisation: "SUNDAY SCHOOL" },
  { date: "2026-09-23", activity: "WARD FAMILY HISTORY WORKSHOP", organisation: "WARD" },
  { date: "2026-09-26", activity: "YOUNG WOMEN SPORTING ACTIVITY", organisation: "YOUNG WOMEN" },
  { date: "2026-09-27", activity: "WARD TEMPLE AND FAMILY HISTORY DEVOTIONAL", organisation: "WARD" },
  { date: "2026-10-10", activity: "WARD MISSIONARY FIRESIDE/REACTIVATION ACTIVITIES", organisation: "WARD" },
  { date: "2026-10-25", activity: "NEW AND RETURNING MEMBERS DEVOTIONAL/FIRESIDE", organisation: "WARD" },
  { date: "2026-10-31", activity: "YOUNG MEN SERVICE PROJECT", organisation: "YOUNG MEN" },
  { date: "2026-10-31", activity: "YSA MOVIE NIGHT", organisation: "YSA" },
  { date: "2026-11-01", activity: "ALL ENDOWED MEMBERS DEVOTIONAL", organisation: "WARD" },
  { date: "2026-11-07", activity: "YOUNG MEN SPORTING ACTIVITY", organisation: "YOUNG MEN" },
  { date: "2026-11-07", activity: "PRIMARY TALENT SHOW", organisation: "PRIMARY" },
  { date: "2026-11-07", activity: "YOUNG WOMEN A DAY WITH MOTHERS", organisation: "YOUNG WOMEN" },
  { date: "2026-11-21", activity: "WARD COUPLES DAY ACTIVITY", organisation: "WARD" },
  { date: "2026-12-03", activity: "WARD FAMILY HISTORY WORKSHOP", organisation: "WARD" },
  { date: "2026-12-05", activity: "YOUNG WOMEN END OF YEAR DEVOTIONAL", organisation: "YOUNG WOMEN" },
  { date: "2026-12-05", activity: "YSA LOVE FEAST", organisation: "YSA" },
  { date: "2026-12-06", activity: "WARD TEMPLE AND FAMILY HISTORY DEVOTIONAL", organisation: "WARD" },
  { date: "2026-12-20", activity: "WARD CHRISTMAS/END OF THE YEAR ACTIVITY", organisation: "WARD" }
];
